//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具產生。
//     執行時版本:4.0.30319.42000
//
//     對此檔案的變更可能會導致不正確的行為，並且若果
//     重新產生程式碼，這些變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNotificationApp.Properties {
    using System;
    
    
    /// <summary>
    ///   一個強型態的資源類別，用於查詢本機化的字串等。
    /// </summary>
    // 此類別是由 StronglyTypedResourceBuilder
    // 類別透過類別似於 ResGen 或 Visual Studio 的工具自動產生的。
    // 若要加入或移除成員，請編輯 .ResX 檔案，然後重新執行 ResGen
    // (以 /str 作為指令選項)，或重新產生 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回此類別使用的快取的 ResourceManager 案例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PushNotificationApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此強型態資源類別，為所有資源查詢
        ///   重新定義目前執行緒的 CurrentUICulture 屬性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
