//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具產生。
//     執行時版本:4.0.30319.42000
//
//     對此檔案的變更可能會導致不正確的行為，並且若果
//     重新產生程式碼，這些變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNotificationApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
